=== angeldelblanco/eadventure-legacy/E-Adventure/eadventure-tracking-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://e-adventure.e-ucm.es/eadventure-tracking-schema" xmlns:tns="http://e-adventure.e-ucm.es/eadventure-tracking-schema" elementFormDefault="qualified">
	
	<xs:element name="enabled" type="xs:boolean" default="false"/>
	<xs:element name="main-class" type="xs:string"/>
	
	<xs:element name="class" type="xs:string"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="value" type="xs:string"/>
	<xs:element name="frequency" type="xs:long" default="5000"/>
	<xs:element name="url" type="xs:string"/>
	<xs:element name="path" type="xs:string"/>
	
	<xs:element name="property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:name"/>
				<xs:element ref="tns:value"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:enabled" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="tns:name"  minOccurs="1" maxOccurs="1"/>
				<xs:element ref="tns:class"  minOccurs="0" maxOccurs="1"/>
				<xs:element ref="tns:frequency"  minOccurs="0" maxOccurs="1"/>
				<xs:element ref="tns:url"  minOccurs="0" maxOccurs="1"/>
				<xs:element ref="tns:path"  minOccurs="0" maxOccurs="1"/>
				<xs:element ref="tns:property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="tracking-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tns:enabled" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="tns:main-class"  minOccurs="0" maxOccurs="1"/>
				<xs:element ref="tns:property" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="tns:service" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="a"></xs:element>
</xs:schema>

=== angeldelblanco/eadventure-legacy/E-Adventure/eadventure-tracking-schema-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:tracking-config xmlns:tns="http://e-adventure.e-ucm.es/eadventure-tracking-schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://e-adventure.e-ucm.es/eadventure-tracking-schema eadventure-tracking-schema.xsd ">
	
	<tns:enabled>true</tns:enabled>
	<tns:main-class>es.eucm.eadventure.tracking.prv.TrackingController</tns:main-class>
	
	<tns:property>
	    <tns:name>game-id</tns:name>
	    <tns:value>damaboba_v5b</tns:value>
	</tns:property>
	
	<tns:property>
	    <tns:name>student-id</tns:name>
	    <tns:value>ask</tns:value>
	</tns:property>
	
	<tns:property>
	    <tns:name>log-effects</tns:name>
	    <tns:value>true</tns:value>
	</tns:property>
	
	<tns:property>
	    <tns:name>low-level-freq</tns:name>
	    <tns:value>500</tns:value>
	</tns:property>
	
	<tns:service>
	    <tns:enabled>true</tns:enabled>
	    <tns:name>local-log</tns:name>
	    <tns:class>es.eucm.eadventure.tracking.prv.service.GameLogConsumerLocal</tns:class>
	    <tns:frequency>10000</tns:frequency>
	</tns:service>
	
	<tns:service>
	    <tns:enabled>true</tns:enabled>
	    <tns:name>remote-log</tns:name>
	    <tns:class>es.eucm.eadventure.tracking.prv.service.GameLogConsumerHTTP</tns:class>
	    <tns:frequency>5000</tns:frequency>
	    <tns:url>backend-ea.e-ucm.es/api/sessions/</tns:url>
	    <tns:path>chunks</tns:path>
	</tns:service>
	
</tns:tracking-config>
